# -*- coding: utf-8 -*-
"""deepaksteeleye.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18jqRCZqLBRpVRvmdNP20gd4Q-Gp7mCQI
"""

from bs4 import BeautifulSoup
import pandas as pd
fin = open("/content/drive/MyDrive/DLTINS_20210117_01of01.xml", "r")
fout = open("out.xml", "w")
for line in fin:
	fout.write(line.replace('EUPublicDLTINS_20210117_01of01auth.036.001.02', ''))
fin.close()
fout.close()
document_file = open("out.xml", "r")
original_doc = document_file.read()
soup = BeautifulSoup(original_doc, 'xml')

id=[]
name=[]
clss=[]
cmmdty=[]
ntnl=[]
issr=[]

Id = soup.find_all('Id')
for i in Id:
    id.append(i.text) 
Id=[]
for i in id:
  if len(i)==12:
    Id.append(i)

FullNm= soup.find_all('FullNm')
for i in FullNm:
    name.append(i.text) 

ClssfctnTp = soup.find_all('ClssfctnTp')
for i in ClssfctnTp:
    clss.append(i.text) 

CmmdtyDerivInd = soup.find_all('CmmdtyDerivInd')
for i in CmmdtyDerivInd:
    cmmdty.append(i.text) 

NtnlCcy = soup.find_all('NtnlCcy')
for i in NtnlCcy:
    ntnl.append(i.text) 
    
Issr = soup.find_all('Issr')
for i in Issr:
    issr.append(i.text) 

dict = {'Id': Id, 'FullNm': name, 'ClssfctnTp': clss, 'CmmdtyDerivInd': cmmdty, 'NtnlCcy': ntnl, 'Issr': issr } 
df = pd.DataFrame(dict)
df.head()
df.to_csv('steeleyeDeepak.csv')

df.head()

